services:
  database:
    container_name: holidex-database
    build: ./database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
      MYSQL_DATABASE: sunnydb
      MYSQL_TCP_PORT: "3306"
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  localstack:
    container_name: holidex-localstack
    build: ./localstack
    environment:
      SERVICES: s3
      DEBUG: "1"
    ports:
      - "4566:4566"
    volumes:
      - ./localstack/init:/etc/localstack/init
      - ./localstack/data:/var/lib/localstack

  io:
    container_name: holidex-io
    build: ./io
    ports:
      - "3004:3004"

  backend:
    container_name: holidex-backend
    build: ./backend
    environment:
      NODE_ENV: compose
      JWT_SECRET: jwtSecret
      APP_SECRET: secret
    ports:
      - "3020:3000"
    depends_on:
      database:
        condition: service_healthy
      localstack:
        condition: service_started
      io:
        condition: service_started

  frontend:
    container_name: holidex-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.compose
    ports:
      - "3012:80"
    depends_on:
      backend:
        condition: service_started
      io:
        condition: service_started
